version: 0.0
os: linux
files:
  - source: /
    #destination: /var/www/coachtech-flea-market-app-main/src
    destination: /home/ec2-user/coachtech-flea-market-app-main/src

permissions:
  -  #object: /var/www/coachtech-flea-market-app-main/src
  - object: /home/ec2-user/coachtech-flea-market-app-main/src
    owner: coachtech-flea-market-app-main
    group: coachtech-flea-market-app-main

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: coachtech-flea-market-app-main
