version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ec2-user/coachtech-flea-market-app-main/src
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 200
      runas: ec2-user
